import './style.css'
import QRCode from 'qrcode'
import {createClient} from '@supabase/supabase-js'
import {queueEvent,pendingEvents,flush} from './sync.js'

const url=import.meta.env.VITE_SUPABASE_URL||''
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||''
const sb=url&&key?createClient(url,key):null
const app=document.querySelector('#app')
const STORAGE='rcdj09-session'
let s={role:'director',judge:null,competition:null,member:null,driver:null,online:navigator.onLine}
let page='home'
let pendingJoinCode=''
let pendingRegisterCode=''
try{Object.assign(s,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}
const $=x=>document.querySelector(x)
function save(){localStorage.setItem(STORAGE,JSON.stringify(s))}
async function auth(){if(!sb)throw new Error('Backend is not configured.');const session=await sb.auth.getSession();if(!session.data.session){const r=await sb.auth.signInAnonymously();if(r.error)throw r.error}return (await sb.auth.getUser()).data.user}
async function audit(action,payload={}){if(!sb||!s.competition||!s.member)return;const u=await sb.auth.getUser();const event={competition_id:s.competition.id,actor_user_id:u.data.user?.id,actor_member_id:s.member.id,action,payload,idempotency_key:crypto.randomUUID()};try{await sb.from('audit_log').insert(event)}catch{queueEvent({type:'audit',...event})}}
async function sendQueued(e){if(!sb)throw new Error('No backend');if(e.type==='audit')return sb.from('audit_log').insert(e);if(e.type==='judge_decision')return sb.from('judge_decisions').insert(e);if(e.type==='judge_call')return sb.from('judge_calls').insert(e)}
function newCode(){return crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(-6).toUpperCase()}
function shortCode(v){return String(v||'').toUpperCase()}
function registrationUrl(code){return `${location.origin}${location.pathname}?register=${encodeURIComponent(code)}`}
function judgeUrl(code){return `${location.origin}${location.pathname}?join=${encodeURIComponent(code)}`}
async function create(){if(!sb)return alert('Backend is not configured.');try{const user=await auth();const name=$('#competitionName').value.trim()||'RC Drift Competition';const judges=Number(document.querySelector('input[name="judgeCount"]:checked')?.value||3);const code=newCode();const driverCode=newCode();const {data:c,error}=await sb.from('competitions').insert({name,join_code:code,driver_registration_code:driverCode,judge_count:judges,created_by:user.id}).select().single();if(error)throw error;const displayName=$('#directorName').value.trim()||'Director';const {data:m,error:me}=await sb.from('members').insert({competition_id:c.id,user_id:user.id,display_name:displayName,role:'director'}).select().single();if(me)throw me;s={...s,competition:c,member:m,role:'director',judge:null,driver:null};page='home';save();subscribe();render()}catch(e){alert(e.message)}}
async function join(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=shortCode($('#code').value||pendingJoinCode);const name=$('#name').value.trim()||'Judge';const role=s.role==='display'?'display':'judge';const {data,error}=await sb.rpc('join_competition_by_code',{p_code:code,p_display_name:name,p_role:role});if(error)throw new Error(error.message||'Unable to join competition.');if(!data?.length)throw new Error('Competition code not found.');const r=data[0];const {data:c,error:ce}=await sb.from('competitions').select('*').eq('id',r.competition_id).single();if(ce)throw ce;s={...s,competition:c,member:{id:r.member_id},role,judge:r.judge_number??null};pendingJoinCode='';page='home';save();subscribe();render()}catch(e){alert(e.message)}}
async function registerDriver(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=shortCode($('#driverCode').value||pendingRegisterCode);const name=$('#driverName').value.trim();const team=$('#teamName').value.trim();if(!name)return alert('Please enter your driver name.');const {data,error}=await sb.rpc('register_driver',{p_registration_code:code,p_name:name,p_team_name:team||null});if(error)throw new Error(error.message||'Unable to register.');const r=data?.[0];if(!r)throw new Error('Registration failed.');s={...s,driver:r,competition:{id:r.competition_id,name:r.competition_name},member:null,role:'competitor'};pendingRegisterCode='';page='home';save();render()}catch(e){alert(e.message)}}
async function rejoinDriver(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=shortCode($('#rejoinCode').value);if(!code)return alert('Enter your rejoin code.');const {data,error}=await sb.rpc('rejoin_driver',{p_rejoin_code:code});if(error)throw new Error(error.message||'Unable to rejoin.');const r=data?.[0];if(!r)throw new Error('Rejoin code not found.');s={...s,driver:r,competition:{id:r.competition_id,name:r.competition_name},member:null,role:'competitor'};page='home';save();render()}catch(e){alert(e.message)}}
async function rejoinJudge(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=shortCode($('#rejoinCode').value);if(!code)return alert('Enter your rejoin code.');const {data,error}=await sb.rpc('rejoin_judge',{p_rejoin_code:code});if(error)throw new Error(error.message||'Unable to rejoin.');const r=data?.[0];if(!r)throw new Error('Rejoin code not found.');const {data:c,error:ce}=await sb.from('competitions').select('*').eq('id',r.competition_id).single();if(ce)throw ce;s={...s,competition:c,member:{id:r.member_id},role:'judge',judge:r.judge_number};page='home';save();subscribe();render()}catch(e){alert(e.message)}}
function subscribe(){if(!sb||!s.competition?.id)return;const id=s.competition.id;sb.channel(`competition:${id}`).on('postgres_changes',{event:'*',schema:'public',table:'competitions',filter:`id=eq.${id}`},()=>refreshCompetition()).subscribe()}
async function refreshCompetition(){if(!sb||!s.competition?.id)return;const {data}=await sb.from('competitions').select('*').eq('id',s.competition.id).single();if(data){s.competition=data;save();render()}}
async function loadInviteContext(){if(!sb)return;try{if(pendingRegisterCode){const {data,error}=await sb.from('competitions').select('id,name').eq('driver_registration_code',pendingRegisterCode).single();if(!error&&data)s.inviteCompetition=data}if(pendingJoinCode){const {data,error}=await sb.from('competitions').select('id,name').eq('join_code',pendingJoinCode).single();if(!error&&data)s.inviteCompetition=data}}catch{}}
async function showQr(id,text){const el=document.getElementById(id);if(!el)return;try{el.innerHTML='';const canvas=document.createElement('canvas');await QRCode.toCanvas(canvas,text,{width:220,margin:2});el.appendChild(canvas)}catch{el.textContent='QR unavailable'}}
async function submitDecision(decision){if(!sb||!s.competition)return;const battleId=s.competition.active_battle_id;if(!battleId)return alert('No active battle.');const row={battle_id:battleId,judge_member_id:s.member.id,run_number:s.competition.active_run,decision,idempotency_key:crypto.randomUUID()};try{const {error}=await sb.from('judge_decisions').upsert(row,{onConflict:'battle_id,judge_member_id,run_number'});if(error)throw error;await audit('judge_decision',{decision,run:s.competition.active_run});alert('Decision submitted.')}catch{queueEvent({type:'judge_decision',...row});alert('Network unavailable — decision queued for retry.')}}
async function submitCall(type){if(!sb||!s.competition)return;const battleId=s.competition.active_battle_id;if(!battleId)return alert('No active battle.');const row={battle_id:battleId,judge_member_id:s.member.id,run_number:s.competition.active_run,call_type:type,idempotency_key:crypto.randomUUID()};try{const {error}=await sb.from('judge_calls').insert(row);if(error)throw error;await audit('judge_call',{type});alert(type+' recorded.')}catch{queueEvent({type:'judge_call',...row});alert('Network unavailable — call queued for retry.')}}
async function setPhase(phase){if(!sb||!s.competition)return;const {error}=await sb.from('competitions').update({current_phase:phase,status:'live'}).eq('id',s.competition.id);if(!error){await audit('phase_changed',{phase});await refreshCompetition()}}
function homeView(){return `<section class="card hero"><h2>RC Drift Competition</h2><p class="muted">Create an event, join one, or register as a competitor.</p><button id="showCreate" class="primary">Create Competition</button><button id="showJoin">Join Competition</button><button id="showDriver">Register as Competitor</button><button id="showRejoin">Already registered? Rejoin</button></section>`}
function createView(){return `<section class="card hero"><h2>Create Competition</h2><input id="competitionName" placeholder="Competition name"><input id="directorName" placeholder="Director name"><p>Number of judges</p><div class="roles"><label><input type="radio" name="judgeCount" value="2"> 2</label><label><input type="radio" name="judgeCount" value="3" checked> 3</label></div><button id="create" class="primary">Create Competition</button><button id="back">Back</button></section>`}
function joinView(){const invite=s.inviteCompetition;return `<section class="card hero"><h2>Join Competition</h2>${invite?`<p class="muted">Joining <b>${invite.name}</b> as a judge.</p>`:'<p class="muted">Enter the competition access code.</p>'}<input id="code" value="${pendingJoinCode}" placeholder="Access code" ${pendingJoinCode?'readonly':''}><input id="name" placeholder="Your name"><button id="join" class="primary">Join as Judge</button><button id="back">Back</button></section>`}
function driverView(){if(s.driver)return `<section class="card hero"><small>COMPETITOR</small><h2>You're registered!</h2><p>${s.driver.competition_name}</p><div class="code">Car #${s.driver.car_number}</div><p>${s.driver.name||''}</p><div class="code">${s.driver.rejoin_code||'—'}</div><p class="muted">Your two-character rejoin code. Keep it somewhere safe.</p><button id="home">Done</button></section>`;const invite=s.inviteCompetition;return `<section class="card hero"><h2>Register as Competitor</h2>${invite?`<p class="muted">Registering for <b>${invite.name}</b></p>`:'<p class="muted">Enter the competition registration code.</p>'}<input id="driverCode" value="${pendingRegisterCode}" placeholder="Registration code" ${pendingRegisterCode?'readonly':''}><input id="driverName" placeholder="Driver name"><input id="teamName" placeholder="Team name (optional)"><button id="registerDriver" class="primary">Register</button><button id="back">Back</button></section>`}
function rejoinView(){return `<section class="card hero"><h2>Rejoin</h2><p class="muted">Use your two-character code to restore your competitor or judge session.</p><input id="rejoinCode" maxlength="2" autocapitalize="characters" placeholder="A9"><div class="roles"><button id="rejoinDriver" class="primary">Rejoin as Competitor</button><button id="rejoinJudge">Rejoin as Judge</button></div><button id="back">Back</button></section>`}
function directorView(){const driverCode=s.competition.driver_registration_code||'Unavailable';return `<section class="card"><small>DIRECTOR</small><h2>${s.competition.name}</h2><p class="muted">Judge access</p><div class="code">${s.competition.join_code}</div><div class="qrWrap"><div id="judgeQr"></div><p>Scan to join as Judge</p></div><p class="muted">Driver registration</p><div class="code">${driverCode}</div><div class="qrWrap"><div id="driverQr"></div><p>Scan to register as Competitor</p></div><button class="big" id="qual">Start Qualifying</button><button class="big" id="tan">Start Tandem</button><button class="big" id="display">Open Live Display</button></section>`}
function judgeView(){return `<section class="card"><small>JUDGE ${s.judge}</small><h2>Current decision</h2><p>${s.competition.name}</p><p>Run ${s.competition.active_run||1}</p><div class="decisions"><button data-v="A">Driver A</button><button data-v="B">Driver B</button><button data-v="OMT">OMT</button></div><div class="special"><button data-c="Contact">⚠ Contact</button><button data-c="Special Situation">⚠ Special</button></div><p class="muted">Other judges' decisions are not presented here.</p><p>Queued offline events: <b>${pendingEvents().length}</b></p></section>`}
function displayView(){return `<section class="card live"><small>LIVE DISPLAY</small><h2>${s.competition.current_phase||'Waiting'}</h2><p>Active run: ${s.competition.active_run||1}</p></section>`}
async function render(){const params=new URLSearchParams(location.search);if(params.has('register')){pendingRegisterCode=shortCode(params.get('register'));page='driver';await loadInviteContext()}else if(params.has('join')){pendingJoinCode=shortCode(params.get('join'));s.role='judge';page='join';await loadInviteContext()}if(!s.competition){app.innerHTML=`<main><header><div><h1>RC Drift Judge</h1><small>v1.0 Competition Sessions</small></div><span class="statusdot ${s.online?'on':''}"></span></header>${page==='create'?createView():page==='join'?joinView():page==='driver'?driverView():page==='rejoin'?rejoinView():homeView()}</main>`}else app.innerHTML=`<main><header><div><h1>RC Drift Judge</h1><small>v1.0 Competition Sessions</small></div><span class="statusdot ${s.online?'on':''}"></span></header>${s.role==='director'?directorView():s.role==='judge'?judgeView():s.role==='competitor'?driverView():displayView()}</main>`;bind();if(s.competition&&s.role==='director'){showQr('judgeQr',judgeUrl(s.competition.join_code));showQr('driverQr',registrationUrl(s.competition.driver_registration_code))}}
function bind(){document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>submitDecision(b.dataset.v));document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>submitCall(b.dataset.c));const j=$('#join');if(j)j.onclick=join;const c=$('#create');if(c)c.onclick=create;const rd=$('#registerDriver');if(rd)rd.onclick=registerDriver;const rjd=$('#rejoinDriver');if(rjd)rjd.onclick=rejoinDriver;const rjj=$('#rejoinJudge');if(rjj)rjj.onclick=rejoinJudge;const sc=$('#showCreate');if(sc)sc.onclick=()=>{page='create';render()};const sj=$('#showJoin');if(sj)sj.onclick=()=>{s.role='judge';page='join';pendingJoinCode='';s.inviteCompetition=null;render()};const sd=$('#showDriver');if(sd)sd.onclick=()=>{page='driver';pendingRegisterCode='';s.inviteCompetition=null;render()};const sr=$('#showRejoin');if(sr)sr.onclick=()=>{page='rejoin';render()};const back=$('#back');if(back)back.onclick=()=>{page='home';pendingJoinCode='';pendingRegisterCode='';s.inviteCompetition=null;render()};const home=$('#home');if(home)home.onclick=()=>{page='home';render()};const q=$('#qual');if(q)q.onclick=()=>setPhase('qualifying');const t=$('#tan');if(t)t.onclick=()=>setPhase('tandem');const d=$('#display');if(d)d.onclick=()=>{s.role='display';render()}}
window.addEventListener('online',async()=>{s.online=true;if(sb)await flush(sendQueued);render()});window.addEventListener('offline',()=>{s.online=false;render()});render()
