import './style.css'
import QRCode from 'qrcode'
import {createClient} from '@supabase/supabase-js'
import {queueEvent,pendingEvents,flush} from './sync.js'

const url=import.meta.env.VITE_SUPABASE_URL||''
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||''
const sb=url&&key?createClient(url,key):null
const app=document.querySelector('#app')
let s={role:'director',judge:null,competition:null,member:null,online:navigator.onLine}
const $=x=>document.querySelector(x)
function save(){localStorage.setItem('rcdj09-session',JSON.stringify(s))}
function load(){try{Object.assign(s,JSON.parse(localStorage.getItem('rcdj09-session')||'{}'))}catch{}}
load()
async function audit(action,payload={}){if(!sb||!s.competition||!s.member)return;const u=await sb.auth.getUser();const event={competition_id:s.competition.id,actor_user_id:u.data.user?.id,actor_member_id:s.member.id,action,payload,idempotency_key:crypto.randomUUID()};try{await sb.from('audit_log').insert(event)}catch{queueEvent({type:'audit',...event})}}
async function sendQueued(e){if(!sb)throw new Error('No backend');if(e.type==='audit')return sb.from('audit_log').insert(e);if(e.type==='judge_decision')return sb.from('judge_decisions').insert(e);if(e.type==='judge_call')return sb.from('judge_calls').insert(e)}
async function auth(){if(!sb)throw new Error('Backend is not configured.');const session=await sb.auth.getSession();if(!session.data.session){const r=await sb.auth.signInAnonymously();if(r.error)throw r.error}return (await sb.auth.getUser()).data.user}
function newCode(){return crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(-6).toUpperCase()}
async function create(){if(!sb)return alert('Backend is not configured.');try{const user=await auth();const name=$('#competitionName').value.trim()||'RC Drift Competition';const judges=Number(document.querySelector('input[name="judgeCount"]:checked')?.value||3);const code=newCode();const {data:c,error}=await sb.from('competitions').insert({name,join_code:code,judge_count:judges,created_by:user.id}).select().single();if(error)throw error;const displayName=$('#directorName').value.trim()||'Director';const {data:m,error:me}=await sb.from('members').insert({competition_id:c.id,user_id:user.id,display_name:displayName,role:'director'}).select().single();if(me)throw me;s={...s,competition:c,member:m,role:'director',judge:null};save();subscribe();render()}catch(e){alert(e.message)}}
async function join(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=$('#code').value.trim().toUpperCase();const name=$('#name').value.trim()||'Judge';const role=s.role;const {data,error}=await sb.rpc('join_competition_by_code',{p_code:code,p_display_name:name,p_role:role});if(error)throw new Error(error.message||'Unable to join competition.');if(!data||!data.length)throw new Error('Competition code not found.');const r=data[0];const {data:c,error:ce}=await sb.from('competitions').select('*').eq('id',r.competition_id).single();if(ce)throw ce;s={...s,competition:c,member:{id:r.member_id},role,judge:r.judge_number??null};save();subscribe();render()}catch(e){alert(e.message)}}
async function registerDriver(){if(!sb)return alert('Backend is not configured.');try{await auth();const code=$('#driverCode').value.trim().toUpperCase();const name=$('#driverName').value.trim();const team=$('#teamName').value.trim();if(!name)return alert('Please enter your driver name.');const {data,error}=await sb.rpc('register_driver',{p_registration_code:code,p_name:name,p_team_name:team||null});if(error)throw new Error(error.message||'Unable to register.');const r=data?.[0];if(!r)throw new Error('Registration failed.');s={...s,driver:r,role:'competitor'};save();render()}catch(e){alert(e.message)}}
function subscribe(){if(!sb||!s.competition)return;const id=s.competition.id;sb.channel(`competition:${id}`).on('postgres_changes',{event:'*',schema:'public',table:'competitions',filter:`id=eq.${id}`},()=>refreshCompetition()).subscribe()}
async function refreshCompetition(){if(!sb||!s.competition)return;const {data}=await sb.from('competitions').select('*').eq('id',s.competition.id).single();if(data){s.competition=data;save();render()}}
async function showQr(id,text){const el=document.getElementById(id);if(!el)return;try{el.innerHTML='';const canvas=document.createElement('canvas');await QRCode.toCanvas(canvas,text,{width:220,margin:2});el.appendChild(canvas)}catch(e){el.textContent='QR unavailable'}}
function registrationUrl(code){return `${location.origin}${location.pathname}?register=${encodeURIComponent(code)}`}
async function submitDecision(decision){if(!sb||!s.competition)return;const battleId=s.competition.active_battle_id;if(!battleId)return alert('No active battle.');const row={battle_id:battleId,judge_member_id:s.member.id,run_number:s.competition.active_run,decision,idempotency_key:crypto.randomUUID()};try{const {error}=await sb.from('judge_decisions').upsert(row,{onConflict:'battle_id,judge_member_id,run_number'});if(error)throw error;await audit('judge_decision',{decision,run:s.competition.active_run});alert('Decision submitted.')}catch{queueEvent({type:'judge_decision',...row});alert('Network unavailable — decision queued for retry.')}}
async function submitCall(type){if(!sb||!s.competition)return;const battleId=s.competition.active_battle_id;if(!battleId)return alert('No active battle.');const row={battle_id:battleId,judge_member_id:s.member.id,run_number:s.competition.active_run,call_type:type,idempotency_key:crypto.randomUUID()};try{const {error}=await sb.from('judge_calls').insert(row);if(error)throw error;await audit('judge_call',{type});alert(type+' recorded.')}catch{queueEvent({type:'judge_call',...row});alert('Network unavailable — call queued for retry.')}}
async function setPhase(phase){if(!sb||!s.competition)return;const {error}=await sb.from('competitions').update({current_phase:phase,status:'live'}).eq('id',s.competition.id);if(!error){await audit('phase_changed',{phase});await refreshCompetition()}}
function homeView(){return `<section class="card hero"><h2>RC Drift Competition</h2><p class="muted">Create an event, join one, or register as a competitor.</p><button id="showCreate" class="primary">Create Competition</button><button id="showJoin">Join Competition</button><button id="showDriver">Register as Competitor</button></section>`}
function createView(){return `<section class="card hero"><h2>Create Competition</h2><input id="competitionName" placeholder="Competition name"><input id="directorName" placeholder="Director name"><p>Number of judges</p><div class="roles"><label><input type="radio" name="judgeCount" value="2"> 2</label><label><input type="radio" name="judgeCount" value="3" checked> 3</label></div><button id="create" class="primary">Create Competition</button><button id="back">Back</button></section>`}
function joinView(){return `<section class="card hero"><h2>Join Competition</h2><input id="code" placeholder="Access code"><input id="name" placeholder="Your name"><div class="roles"><button data-role="judge" class="primary">Judge</button><button data-role="display">Live Display</button></div><p class="muted">Judges are automatically assigned the next available position in join order.</p><button id="join" class="primary">Join Competition</button><button id="back">Back</button></section>`}
function driverView(){if(s.driver)return `<section class="card hero"><small>COMPETITOR</small><h2>Registration submitted</h2><p>${s.driver.competition_name}</p><div class="code">Car #${s.driver.car_number}</div><p>${s.driver.name||''}</p><p class="muted">Your registration is pending Director approval.</p></section>`;return `<section class="card hero"><h2>Register as Competitor</h2><input id="driverCode" placeholder="Driver registration code"><input id="driverName" placeholder="Driver name"><input id="teamName" placeholder="Team name (optional)"><button id="registerDriver" class="primary">Submit Registration</button><button id="back">Back</button></section>`}
function directorView(){const driverCode=s.competition.driver_registration_code||'Unavailable';return `<section class="card"><small>DIRECTOR</small><h2>${s.competition.name}</h2><p class="muted">Judge access</p><div class="code">${s.competition.join_code}</div><div class="qrWrap"><div id="judgeQr"></div><p>Scan to join as Judge</p></div><p class="muted">Driver registration</p><div class="code">${driverCode}</div><div class="qrWrap"><div id="driverQr"></div><p>Scan to register as Competitor</p></div><button class="big" id="qual">Start Qualifying</button><button class="big" id="tan">Start Tandem</button><button class="big" id="display">Open Live Display</button></section>`}
function judgeView(){return `<section class="card"><small>JUDGE ${s.judge}</small><h2>Current decision</h2><p>Run ${s.competition.active_run||1}</p><div class="decisions"><button data-v="A">Driver A</button><button data-v="B">Driver B</button><button data-v="OMT">OMT</button></div><div class="special"><button data-c="Contact">⚠ Contact</button><button data-c="Special Situation">⚠ Special</button></div><p class="muted">Other judges' decisions are not presented here.</p><p>Queued offline events: <b>${pendingEvents().length}</b></p></section>`}
function displayView(){return `<section class="card live"><small>LIVE DISPLAY</small><h2>${s.competition.current_phase||'Waiting'}</h2><p>Active run: ${s.competition.active_run||1}</p></section>`}
let page='home'
function render(){if(new URLSearchParams(location.search).has('register'))page='driver';app.innerHTML=`<main><header><div><h1>RC Drift Judge</h1><small>v1.0 Competition Sessions</small></div><span class="statusdot ${s.online?'on':''}"></span></header>${!s.competition?(page==='create'?createView():page==='join'?joinView():page==='driver'?driverView():homeView()):s.role==='director'?directorView():s.role==='judge'?judgeView():s.role==='competitor'?driverView():displayView()}</main>`;bind();if(s.competition&&s.role==='director'){showQr('judgeQr',`${location.origin}${location.pathname}?join=${encodeURIComponent(s.competition.join_code)}`);showQr('driverQr',registrationUrl(s.competition.driver_registration_code))}}
function bind(){document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{s.role=b.dataset.role;render()});const j=$('#join');if(j)j.onclick=join;const c=$('#create');if(c)c.onclick=create;const rd=$('#registerDriver');if(rd)rd.onclick=registerDriver;const sc=$('#showCreate');if(sc)sc.onclick=()=>{page='create';render()};const sj=$('#showJoin');if(sj)sj.onclick=()=>{page='join';render()};const sd=$('#showDriver');if(sd)sd.onclick=()=>{page='driver';render()};const back=$('#back');if(back)back.onclick=()=>{page='home';render()};document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>submitDecision(b.dataset.v));document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>submitCall(b.dataset.c));const q=$('#qual');if(q)q.onclick=()=>setPhase('qualifying');const t=$('#tan');if(t)t.onclick=()=>setPhase('tandem');const d=$('#display');if(d)d.onclick=()=>{s.role='display';render()}}
window.addEventListener('online',async()=>{s.online=true;if(sb)await flush(sendQueued);render()});window.addEventListener('offline',()=>{s.online=false;render()});render()
